name: Java Tests Maven 4.0.0-rc-5

on: [push, pull_request]

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  maven-version: 4.0.0-rc-5

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: Tests Maven 4.0.0-rc-5 with java 25

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          cache: maven
          distribution: zulu
          java-version: 25
      - name: Set Maven Wrapper version ${{ env.maven-version }}
        run: sed -i "s|^distributionUrl=.*|distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/${{ env.maven-version }}/apache-maven-${{ env.maven-version }}-bin.zip|" .mvn/wrapper/maven-wrapper.properties
      - name: Test with Maven ${{ env.maven-version }}
        run: ./mvnw test --batch-mode --no-transfer-progress --show-version -Dlicense.skip=true -Dmaven=${{ env.maven-version }} -Dmaven.min-version=${{ env.maven-version }}
