name: Java Tests Maven 3.6.3

on: [push, pull_request]

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  maven-version: 3.6.3

jobs:
  test:
    runs-on: windows-latest
    timeout-minutes: 30
    name: Tests Maven 3.6.3 with java 21

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          cache: maven
          distribution: zulu
          java-version: 21
      - name: Set Maven Wrapper version ${{ env.maven-version }}
        run: sed -i "s|^distributionUrl=.*|distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/${{ env.maven-version }}/apache-maven-${{ env.maven-version }}-bin.zip|" .mvn/wrapper/maven-wrapper.properties
      - name: Set 'project.basedir' to 'basedir' for more broad maven ${{ env.maven-version }} support
        run: sed -i "s|project.basedir|basedir|" pom.xml
      - name: Test with Maven ${{ env.maven-version }}
        run: ./mvnw test --batch-mode --no-transfer-progress --show-version -D"license.skip=true" -D"maven=${{ env.maven-version }}" -D"maven.min-version=${{ env.maven-version }}"
