name: Java Integration Tests Maven 4.0.0-beta-4

on: [push, pull_request]

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  maven-version: 4.0.0-rc-4

jobs:
  test:
    runs-on: ubuntu-latest
    name: Integration Tests Maven 4.0.0-rc-4 with java 25

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Set up JDK
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
        with:
          cache: maven
          distribution: zulu
          java-version: 25
      - name: Set Maven Wrapper version ${{ env.maven-version }}
        run: sed -i "s|^distributionUrl=.*|distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/${{ env.maven-version }}/apache-maven-${{ env.maven-version }}-bin.zip|" .mvn/wrapper/maven-wrapper.properties
      - name: Integration Test with Maven ${{ env.maven-version }}
        run: ./mvnw verify --batch-mode --no-transfer-progress --show-version -Dlicense.skip=true -Dmaven.min-version=${{ env.maven-version }} -Prun-it
